# Generated by Django 4.2.3 on 2023-07-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0004_alter_album_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='value',
        ),
        migrations.AddField(
            model_name='album',
            name='number_of_sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
